### ISSUE TITLE
Fix e2e protractor

### ISSUE THREAD

**Issue by mkoertgen** [awesome-inc/angular-cli#5]
As of now, there still seems to be a bug [angular/protractor/issues/4601](https://github.com/angular/protractor/issues/4601) 
which cannot be easily worked around. The error message goes something like this

```console
webpack: Compiled successfully.
[10:52:54] I/file_manager - creating folder /build/node_modules/webdriver-manager/selenium
[10:52:57] I/update - chromedriver: unzipping chromedriver_2.34.zip
[10:52:57] I/update - chromedriver: setting permissions to 0755 for /build/node_modules/webdriver-manager/selenium/chromedriver_2.34
[10:52:57] I/launcher - Running 1 instances of WebDriver
[10:52:57] I/direct - Using ChromeDriver directly...
[10:52:57] E/launcher - spawn /build/node_modules/webdriver-manager/selenium/chromedriver_2.34 ENOENT
[10:52:57] E/launcher - Error: spawn /build/node_modules/webdriver-manager/selenium/chromedriver_2.34 ENOENT
    at _errnoException (util.js:1019:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[10:52:57] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'myapp' failed to build: The command '/bin/sh -c yarn run e2e' returned a non-zero code: 1
```

**Comment by mkoertgen** [comment]
Fixed with 6.0.7
